version: '3.9'
services:
  fibonacci-api:
    build: .
    ports:
      - "50051:50051" # gRPC API
      - "9091:9091"   # HTTP метрики
    environment:
      - REDIS_ADDR=redis:6379
      - PROMETHEUS_ADDR=http://prometheus:9091
    depends_on:
      - redis
      - prometheus
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
